### ISSUE TITLE
First Release Checklist

### ISSUE THREAD

**Issue by AustinEast** [Ogmo-Editor-3/OgmoEditor3-CE#23]
This issue is for discussing what we need to get done before we make an initial release of the App.

- [x] Tile/Grid selection tools #3 
- [x] Filetree optimization #15 
- [x] Array data exported as Arrays instead of Strings
- [x] Docs (what all do we need?)
- [x] Tooltips (simple `title` attributes on the icon buttons should be enough for now)
- [x] Set up an electron built tool for packaging (legacy app was using `electron-packager`, I'm personally familiar with `electron-builder`, but no real preference here)
- [x] Determine where to host this stuff (itch, GitHub Pages, etc)
- [x] Get Matt's blessing
